name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # - name: Install iverilog
      #   shell: bash
      #   run: sudo apt-get update && sudo apt-get install -y iverilog
      - name: Install the latest iverilog w/ SDF annotation interconnect support
        shell: bash
        run: |
          cat << EOF >> $GITHUB_ENV
          IVERILOG_ROOT=/home/runner/iverilog
          EOF
          git clone --depth=1 --branch $IVERILOG_TAG https://github.com/steveicarus/iverilog.git $IVERILOG_ROOT
          sudo apt-get install -y autoconf gperf make gcc g++ bison flex
          cd $IVERILOG_ROOT
          make install --prefix=$IVERILOG_ROOT
          export PATH=$IVERILOG_ROOT/bin:$PATH

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install cocotb 1.8.x
        shell: bash
        run: |
          pip install cocotb~=1.8.0
          cocotb-config --libpython
          cocotb-config --python-bin 

      - name: Set up environment variables
        shell: bash
        run: |
          cat << EOF >> $GITHUB_ENV
          PDK_ROOT=/home/runner/pdk
          PDK=sky130A
          EOF
  
      - name: Install Sky130 PDK
        uses: TinyTapeout/volare-action@v2
        with:
          pdk_name: sky130
          pdk_version: cd1748bb197f9b7af62a54507de6624e30363943
          pdk_root: /home/runner/pdk

      - name: Run tests
        run: |
          cd test
          make clean
          make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.2
        with:
          paths: "test/results.xml"
        if: always()           

      - name: Generate JSON waveform
        run: |
          python3 test/tdc_vcd_to_json.py

      - name: upload vcd
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            test/tb.vcd
            test/result.xml

      - name: upload json
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-json
          path: |
            test/tb_wf.json
